import { BarChart3, CheckCircle2, ClipboardList, LogOut, Menu, Settings, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { clearDemoAuth } from '../auth'
import MockComplaints from '../components/reports/MockComplaints'
import IssueQueue from '../components/dashboard/IssueQueue'
import DashboardMap from '../components/dashboard/DashboardMap'

function AdminDashboard() { const navigate = useNavigate(); const [open, setOpen] = useState(false); const [reports, setReports] = useState(MockComplaints); const [department, setDepartment] = useState('All'); const [status, setStatus] = useState('All'); const filtered = useMemo(() => reports.filter((item) => (department === 'All' || item.department === department) && (status === 'All' || item.status === status)), [department, reports, status]); const updateStatus = (id, nextStatus) => setReports((items) => items.map((item) => item.id === id ? { ...item, status: nextStatus } : item)); const stats = [reports.length, reports.filter((item) => ['Reported', 'Verified', 'Assigned'].includes(item.status)).length, reports.filter((item) => item.status === 'In Progress').length, reports.filter((item) => item.status === 'Resolved').length]
 return <main className="authority-page admin-mock-page"><aside className={`authority-sidebar ${open ? 'open' : ''}`}><div className="admin-logo"><span>J</span><strong>JANSETU</strong></div><div className="authority-identity"><span>ADMIN</span><strong>Central Operations</strong><small>All departments</small></div><nav><a className="active" href="#overview"><ClipboardList size={16} /> Overview</a><a href="#queue"><BarChart3 size={16} /> All complaints</a><a href="/settings"><Settings size={16} /> Settings</a></nav><button onClick={() => { clearDemoAuth(); navigate('/login') }}><LogOut size={16} /> Sign out</button></aside><section className="authority-content"><header className="authority-topbar"><button className="authority-menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={20} /> : <Menu size={20} />}</button><div><span className="admin-eyebrow">Government operations / All departments</span><h1>Admin Dashboard</h1><p>Central view of every civic complaint and department.</p></div><CheckCircle2 size={20} /></header><div className="authority-stat-grid">{[['Total Issues', stats[0]], ['Pending', stats[1]], ['In Progress', stats[2]], ['Resolved', stats[3]]].map(([label, value]) => <article key={label}><ClipboardList size={18} /><span>{label}</span><strong>{value}</strong></article>)}</div><section className="admin-filter-bar"><label>Department<select value={department} onChange={(event) => setDepartment(event.target.value)}><option>All</option>{['Roads', 'Electrical', 'Water Supply', 'Sanitation', 'Drainage', 'Public Infrastructure'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>Reported</option><option>Verified</option><option>Assigned</option><option>In Progress</option><option>Resolved</option></select></label></section><div className="authority-overview"><DashboardMap complaints={filtered} /><section className="authority-panel department-overview"><span className="admin-eyebrow">Department overview</span><h2>Ownership by department</h2>{['Roads', 'Electrical', 'Water Supply', 'Sanitation', 'Drainage', 'Public Infrastructure'].map((name) => <div key={name}><strong>{name}</strong><span>{reports.filter((item) => item.department === name).length} complaints</span></div>)}</section></div><div id="queue"><IssueQueue complaints={filtered} onStatusChange={updateStatus} /></div></section></main> }
export default AdminDashboard
