import { useState } from 'react'
import { ArrowRight, Mail, MapPin, Phone } from 'lucide-react'
import { Navbar } from '../App'
import Footer from '../components/Footer'

function ContactUs() {
  const [submitted, setSubmitted] = useState(false)
  function handleSubmit(event) { event.preventDefault(); setSubmitted(true) }
  return <div className="contact-page"><Navbar /><main><header className="contact-hero"><span className="complaint-kicker">Citizen support</span><h1>Contact JanSetu</h1><p>Have a question, suggestion, or need help with a civic report?</p></header><section className="contact-shell"><div className="contact-info"><span className="complaint-label">We are here to help</span><h2>Connect with the civic service team.</h2><div className="contact-info-item"><Mail size={18} /><div><span>Email</span><strong>support@jansetu.gov.in</strong></div></div><div className="contact-info-item"><Phone size={18} /><div><span>Phone</span><strong>1800 123 2026</strong></div></div><div className="contact-info-item"><MapPin size={18} /><div><span>Office</span><strong>JanSetu Civic Service Centre<br />Ranchi, Jharkhand</strong></div></div></div><section className="contact-form-panel">{submitted ? <div className="contact-success"><span>✓</span><h2>Message received.</h2><p>Thank you for contacting JanSetu. Our team will review your message.</p><button type="button" onClick={() => setSubmitted(false)}>Send another message</button></div> : <form onSubmit={handleSubmit}><span className="complaint-label">Send a message</span><div className="contact-form-grid"><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@example.com" /></label><label>Subject<input required placeholder="How can we help?" /></label><label className="contact-message">Message<textarea required rows="5" placeholder="Write your message here" /></label></div><button className="complaint-primary-button" type="submit">Send Message <ArrowRight size={16} /></button></form>}</section></section><section className="faq-section"><span className="complaint-label">Helpful answers</span><h2>Frequently asked questions</h2><div className="faq-grid"><details><summary>How do I report an issue?</summary><p>Use the Report Issue link to provide details, evidence, and a map location.</p></details><details><summary>How can I track a report?</summary><p>Use Explore Reports to browse the current mock civic records and their status timelines.</p></details><details><summary>Is this a real government service?</summary><p>JanSetu is a frontend prototype for demonstrating a digital civic governance experience.</p></details></div></section></main><Footer /></div>
}

export default ContactUs
